include: package:lints/recommended.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error

linter:
  rules:
    - avoid_print: false  # CLI 앱이므로 print 사용 허용
    - prefer_single_quotes: true
    - always_declare_return_types: true
    - avoid_unnecessary_containers: true
    - prefer_const_constructors: true
    - prefer_final_fields: true
