import type { TerminalTheme } from '@/types/settings';

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  theme: TerminalTheme;
}

/**
 * Terminal Theme Presets
 * Popular color schemes for terminal emulators
 */
export const TERMINAL_THEMES: ThemePreset[] = [
  {
    id: 'retro',
    name: 'Retro',
    description: 'Classic green terminal on black background',
    theme: {
      background: '#000000',
      foreground: '#13a10e',
      cursor: '#13a10e',
      cursorAccent: '#000000',
      selectionBackground: '#ffffff',
      black: '#13a10e',
      red: '#13a10e',
      green: '#13a10e',
      yellow: '#13a10e',
      blue: '#13a10e',
      magenta: '#13a10e',
      cyan: '#13a10e',
      white: '#13a10e',
      brightBlack: '#16ba10',
      brightRed: '#16ba10',
      brightGreen: '#16ba10',
      brightYellow: '#16ba10',
      brightBlue: '#16ba10',
      brightMagenta: '#16ba10',
      brightCyan: '#16ba10',
      brightWhite: '#16ba10',
    },
  },
  {
    id: 'apple-system',
    name: 'Apple System Colors',
    description: 'macOS system color palette',
    theme: {
      background: '#1e1e1e',
      foreground: '#ffffff',
      cursor: '#98989d',
      cursorAccent: '#1e1e1e',
      selectionBackground: '#3f638b',
      black: '#1a1a1a',
      red: '#cc372e',
      green: '#26a439',
      yellow: '#cdac08',
      blue: '#0869cb',
      magenta: '#9647bf',
      cyan: '#479ec2',
      white: '#98989d',
      brightBlack: '#464646',
      brightRed: '#ff453a',
      brightGreen: '#32d74b',
      brightYellow: '#ffd60a',
      brightBlue: '#0a84ff',
      brightMagenta: '#bf5af2',
      brightCyan: '#76d6ff',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'cga',
    name: 'CGA',
    description: 'Classic IBM CGA color palette',
    theme: {
      background: '#000000',
      foreground: '#aaaaaa',
      cursor: '#b8b8b8',
      cursorAccent: '#000000',
      selectionBackground: '#c1deff',
      black: '#000000',
      red: '#aa0000',
      green: '#00aa00',
      yellow: '#aa5500',
      blue: '#0000aa',
      magenta: '#aa00aa',
      cyan: '#00aaaa',
      white: '#aaaaaa',
      brightBlack: '#555555',
      brightRed: '#ff5555',
      brightGreen: '#55ff55',
      brightYellow: '#ffff55',
      brightBlue: '#5555ff',
      brightMagenta: '#ff55ff',
      brightCyan: '#55ffff',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'cobalt-neon',
    name: 'Cobalt Neon',
    description: 'Vibrant neon colors on dark blue background',
    theme: {
      background: '#142838',
      foreground: '#8ff586',
      cursor: '#c4206f',
      cursorAccent: '#142838',
      selectionBackground: '#094fb1',
      black: '#142631',
      red: '#ff2320',
      green: '#3ba5ff',
      yellow: '#e9e75c',
      blue: '#8ff586',
      magenta: '#781aa0',
      cyan: '#8ff586',
      white: '#ba46b2',
      brightBlack: '#fff688',
      brightRed: '#d4312e',
      brightGreen: '#8ff586',
      brightYellow: '#e9f06d',
      brightBlue: '#3c7dd2',
      brightMagenta: '#8230a7',
      brightCyan: '#6cbc67',
      brightWhite: '#8ff586',
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    description: 'Dark theme with vibrant pastel colors',
    theme: {
      background: '#1e1f29',
      foreground: '#f8f8f2',
      cursor: '#bbbbbb',
      cursorAccent: '#1e1f29',
      selectionBackground: '#44475a',
      black: '#000000',
      red: '#ff5555',
      green: '#50fa7b',
      yellow: '#f1fa8c',
      blue: '#bd93f9',
      magenta: '#ff79c6',
      cyan: '#8be9fd',
      white: '#bbbbbb',
      brightBlack: '#555555',
      brightRed: '#ff5555',
      brightGreen: '#50fa7b',
      brightYellow: '#f1fa8c',
      brightBlue: '#bd93f9',
      brightMagenta: '#ff79c6',
      brightCyan: '#8be9fd',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'monokai-cmder',
    name: 'Monokai Cmder',
    description: 'Monokai color scheme optimized for Cmder',
    theme: {
      background: '#272822',
      foreground: '#cacaca',
      cursor: '#ffffff',
      cursorAccent: '#272822',
      selectionBackground: '#cccc81',
      black: '#272822',
      red: '#a70334',
      green: '#74aa04',
      yellow: '#b6b649',
      blue: '#01549e',
      magenta: '#89569c',
      cyan: '#1a83a6',
      white: '#cacaca',
      brightBlack: '#7c7c7c',
      brightRed: '#f3044b',
      brightGreen: '#8dd006',
      brightYellow: '#cccc81',
      brightBlue: '#0383f5',
      brightMagenta: '#a87db8',
      brightCyan: '#58c2e5',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'solarized-dark-higher-contrast',
    name: 'Solarized Dark Higher Contrast',
    description: 'Solarized Dark with enhanced contrast',
    theme: {
      background: '#001e27',
      foreground: '#9cc2c3',
      cursor: '#f34b00',
      cursorAccent: '#001e27',
      selectionBackground: '#003748',
      black: '#002831',
      red: '#d11c24',
      green: '#6cbe6c',
      yellow: '#a57706',
      blue: '#2176c7',
      magenta: '#c61c6f',
      cyan: '#259286',
      white: '#eae3cb',
      brightBlack: '#006488',
      brightRed: '#f5163b',
      brightGreen: '#51ef84',
      brightYellow: '#b27e28',
      brightBlue: '#178ec8',
      brightMagenta: '#e24d8e',
      brightCyan: '#00b39e',
      brightWhite: '#fcf4dc',
    },
  },
  {
    id: 'onedark',
    name: 'OneDark',
    description: 'Atom One Dark color scheme',
    theme: {
      background: '#1e2127',
      foreground: '#abb2bf',
      cursor: '#abb2bf',
      cursorAccent: '#1e2127',
      selectionBackground: '#3e4451',
      black: '#1e2127',
      red: '#e06c75',
      green: '#98c379',
      yellow: '#d19a66',
      blue: '#61afef',
      magenta: '#c678dd',
      cyan: '#56b6c2',
      white: '#abb2bf',
      brightBlack: '#5c6370',
      brightRed: '#e06c75',
      brightGreen: '#98c379',
      brightYellow: '#d19a66',
      brightBlue: '#61afef',
      brightMagenta: '#c678dd',
      brightCyan: '#56b6c2',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'material-dark',
    name: 'MaterialDark',
    description: 'Material Design dark theme',
    theme: {
      background: '#232322',
      foreground: '#e5e5e5',
      cursor: '#16afca',
      cursorAccent: '#232322',
      selectionBackground: '#dfdfdf',
      black: '#212121',
      red: '#b7141f',
      green: '#457b24',
      yellow: '#f6981e',
      blue: '#134eb2',
      magenta: '#560088',
      cyan: '#0e717c',
      white: '#efefef',
      brightBlack: '#424242',
      brightRed: '#e83b3f',
      brightGreen: '#7aba3a',
      brightYellow: '#ffea2e',
      brightBlue: '#54a4f3',
      brightMagenta: '#aa4dbc',
      brightCyan: '#26bbd1',
      brightWhite: '#d9d9d9',
    },
  },
  {
    id: 'github-dark',
    name: 'GitHub Dark',
    description: 'GitHub dark color scheme',
    theme: {
      background: '#101216',
      foreground: '#8b949e',
      cursor: '#c9d1d9',
      cursorAccent: '#101216',
      selectionBackground: '#3b5070',
      black: '#000000',
      red: '#f78166',
      green: '#56d364',
      yellow: '#e3b341',
      blue: '#6ca4f8',
      magenta: '#db61a2',
      cyan: '#2b7489',
      white: '#ffffff',
      brightBlack: '#4d4d4d',
      brightRed: '#f78166',
      brightGreen: '#56d364',
      brightYellow: '#e3b341',
      brightBlue: '#6ca4f8',
      brightMagenta: '#db61a2',
      brightCyan: '#2b7489',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'tokyonight',
    name: 'tokyonight',
    description: 'Tokyo Night dark theme',
    theme: {
      background: '#1a1b26',
      foreground: '#c0caf5',
      cursor: '#c0caf5',
      cursorAccent: '#1a1b26',
      selectionBackground: '#33467c',
      black: '#15161e',
      red: '#f7768e',
      green: '#9ece6a',
      yellow: '#e0af68',
      blue: '#7aa2f7',
      magenta: '#bb9af7',
      cyan: '#7dcfff',
      white: '#a9b1d6',
      brightBlack: '#414868',
      brightRed: '#f7768e',
      brightGreen: '#9ece6a',
      brightYellow: '#e0af68',
      brightBlue: '#7aa2f7',
      brightMagenta: '#bb9af7',
      brightCyan: '#7dcfff',
      brightWhite: '#c0caf5',
    },
  },
  {
    id: 'atom-one-light',
    name: 'AtomOneLight',
    description: 'Atom One Light color scheme',
    theme: {
      background: '#f9f9f9',
      foreground: '#2a2c33',
      cursor: '#bbbbbb',
      cursorAccent: '#f9f9f9',
      selectionBackground: '#ededed',
      black: '#000000',
      red: '#de3e35',
      green: '#3f953a',
      yellow: '#d2b67c',
      blue: '#2f5af3',
      magenta: '#950095',
      cyan: '#3f953a',
      white: '#bbbbbb',
      brightBlack: '#000000',
      brightRed: '#de3e35',
      brightGreen: '#3f953a',
      brightYellow: '#d2b67c',
      brightBlue: '#2f5af3',
      brightMagenta: '#a00095',
      brightCyan: '#3f953a',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'clrs',
    name: 'CLRS',
    description: 'Vibrant and clear color scheme',
    theme: {
      background: '#ffffff',
      foreground: '#262626',
      cursor: '#6fd3fc',
      cursorAccent: '#ffffff',
      selectionBackground: '#6fd3fc',
      black: '#000000',
      red: '#f8282a',
      green: '#328a5d',
      yellow: '#fa701d',
      blue: '#135cd0',
      magenta: '#9f00bd',
      cyan: '#33c3c1',
      white: '#b3b3b3',
      brightBlack: '#555753',
      brightRed: '#fb0416',
      brightGreen: '#2cc631',
      brightYellow: '#fdd727',
      brightBlue: '#1670ff',
      brightMagenta: '#e900b0',
      brightCyan: '#3ad5ce',
      brightWhite: '#eeeeec',
    },
  },
  {
    id: 'terminal-basic',
    name: 'Terminal Basic',
    description: 'Basic terminal colors',
    theme: {
      background: '#ffffff',
      foreground: '#000000',
      cursor: '#7f7f7f',
      cursorAccent: '#ffffff',
      selectionBackground: '#a4c9ff',
      black: '#000000',
      red: '#990000',
      green: '#00a600',
      yellow: '#999900',
      blue: '#0000b2',
      magenta: '#b200b2',
      cyan: '#00a6b2',
      white: '#bfbfbf',
      brightBlack: '#666666',
      brightRed: '#e50000',
      brightGreen: '#00d900',
      brightYellow: '#e5e500',
      brightBlue: '#0000ff',
      brightMagenta: '#e500e5',
      brightCyan: '#00e5e5',
      brightWhite: '#e5e5e5',
    },
  },
];

/**
 * Get theme preset by ID
 */
export function getThemeById(id: string): ThemePreset | undefined {
  return TERMINAL_THEMES.find((theme) => theme.id === id);
}

/**
 * Get theme names for dropdown
 */
export function getThemeNames(): Array<{ value: string; label: string }> {
  return TERMINAL_THEMES.map((theme) => ({
    value: theme.id,
    label: theme.name,
  }));
}
